# Two networks
# Each a separate bridge network

apiVersion: knap.github.com/v1alpha1
kind: Network

metadata:
  name: implicit-a
  labels:
    app.kubernetes.io/name: implicit-a
    app.kubernetes.io/component: network

spec:
  provider: bridge

---

apiVersion: knap.github.com/v1alpha1
kind: Network

metadata:
  name: implicit-b
  labels:
    app.kubernetes.io/name: implicit-b
    app.kubernetes.io/component: network

spec:
  provider: bridge

---

# Two deployments
# The first is attached just to network A
# The second is attached to both networks

apiVersion: apps/v1
kind: Deployment

metadata:
  name: knap-hello-world1
  labels:
    app.kubernetes.io/name: knap-hello-world1
    app.kubernetes.io/component: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: knap-hello-world1
      app.kubernetes.io/component: deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: knap-hello-world1
        app.kubernetes.io/component: deployment
      annotations:
        knap.github.com/networks: implicit-a
    spec:
      containers:
      - name: hello-world
        image: docker.io/paulbouwer/hello-kubernetes:1.8
        imagePullPolicy: Always

---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: knap-hello-world2
  labels:
    app.kubernetes.io/name: knap-hello-world2
    app.kubernetes.io/component: deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: knap-hello-world2
      app.kubernetes.io/component: deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: knap-hello-world2
        app.kubernetes.io/component: deployment
      annotations:
        knap.github.com/networks: implicit-a, implicit-b
    spec:
      containers:
      - name: hello-world
        image: docker.io/paulbouwer/hello-kubernetes:1.8
        imagePullPolicy: Always
