// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// NetworkStatusApplyConfiguration represents an declarative configuration of the NetworkStatus type for use
// with apply.
type NetworkStatusApplyConfiguration struct {
	NetworkAttachmentDefinitions []string `json:"networkAttachmentDefinitions,omitempty"`
	Deployments                  []string `json:"deployments,omitempty"`
}

// NetworkStatusApplyConfiguration constructs an declarative configuration of the NetworkStatus type for use with
// apply.
func NetworkStatus() *NetworkStatusApplyConfiguration {
	return &NetworkStatusApplyConfiguration{}
}

// WithNetworkAttachmentDefinitions adds the given value to the NetworkAttachmentDefinitions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NetworkAttachmentDefinitions field.
func (b *NetworkStatusApplyConfiguration) WithNetworkAttachmentDefinitions(values ...string) *NetworkStatusApplyConfiguration {
	for i := range values {
		b.NetworkAttachmentDefinitions = append(b.NetworkAttachmentDefinitions, values[i])
	}
	return b
}

// WithDeployments adds the given value to the Deployments field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Deployments field.
func (b *NetworkStatusApplyConfiguration) WithDeployments(values ...string) *NetworkStatusApplyConfiguration {
	for i := range values {
		b.Deployments = append(b.Deployments, values[i])
	}
	return b
}
