#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../scripts/_env"
. "$ROOT/scripts/_trap"

minikube profile central
kubectl delete --namespace=workspace --wait -f "$ROOT/examples/hello-world/implicit.yaml" || true
knap uninstall --namespace=workspace --wait -v
kubectl delete events --all --namespace=workspace

echo "sudo ip link delete explicit-a || true && exit" | minikube ssh
echo "sudo ip link delete explicit-b || true && exit" | minikube ssh
echo "sudo ip link delete implicit-a || true && exit" | minikube ssh
echo "sudo ip link delete implicit-b || true && exit" | minikube ssh

if [ "$1" == -b ]; then
	"$ROOT/scripts/build-container-images"
	"$ROOT/scripts/publish-container-images"
fi

kubectl config set-context central --namespace=workspace

knap install --wait -v

kubectl apply -f "$ROOT/examples/hello-world/implicit.yaml"

knap logs --follow

# Clean ~/.local/share/containers/ occassionally!
