#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/../scripts/_env"
. "$ROOT/scripts/_trap"

minikube profile central
knap uninstall -n workspace -w -v

if [ "$1" == -b ]; then
	"$ROOT/scripts/build-container-image"
	"$ROOT/scripts/publish-container-image"
fi

kubectl config set-context central --namespace=workspace

knap install -w -v

#knap logs -f

# Clean ~/.local/share/containers/ occassionally!
